export interface ProviderBack{
    provId?:number,
    provCod?:string,
    provCompName?:string,
    provWebSite?:string,
    provEmail?:string,
    provPhone?:string,
    item:{
        itemId?:number,
        itemName?:string
    },
    address:{
        adId?:number,
        adStreet?:string,
        adNumber?:number,
        adZip?:string,
        locality:{
            locId?:number,
            locName?:string,
            province:{
                proId?:number,
                proName?:string
                country:{
                    conId?:number,
                    conName?:string
                }
            }
        }
    },
    provCuit?:string,
    ivaCondition:{
        ivaId?:number,
        ivaCond?:string,
    },
    provLogo?:string,
    infoContact:{
        contId?:number,
        contName?:string,
        contPhone?:string,
        contEmail?:string,
        contRole?:string
    },
    provIsDeleted?:boolean
}